# Generated by Django 3.2.16 on 2023-01-27 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=512)),
                ('arrive_time', models.DateTimeField()),
                ('current_passengers_num', models.IntegerField(default=1)),
                ('vehicle_type', models.CharField(max_length=128, null=True)),
                ('special_request', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CONFIRMED', 'CONFIRMED'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=10)),
                ('can_be_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('earliest_arrive_date', models.DateTimeField(help_text='Format: 2020-01-01 12:00')),
                ('latest_arrive_date', models.DateTimeField(help_text='Format: 2020-01-01 13:00')),
                ('required_passengers_num', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rides.ride')),
            ],
        ),
    ]
