# Generated by Django 3.2.16 on 2023-01-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
