# Generated by Django 3.2.16 on 2023-02-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_auto_20230129_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedrequest',
            old_name='ride_id',
            new_name='ride',
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CONFIRMED', 'CONFIRMED'), ('COMPLETE', 'COMPLETE'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=10),
        ),
    ]
