# Generated by Django 4.1.6 on 2023-02-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0005_auto_20230203_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedrequest",
            name="ride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rides.ride"
            ),
        ),
    ]
